#!/bin/bash
#SBATCH --job-name=Unicycler_test                   #This is the name of your job
#SBATCH --cpus-per-task=16                  #This is the number of cores reserved
#SBATCH --mem-per-cpu=1G              #This is the memory reserved per core.
#Total memory reserved: 16GB

#SBATCH --time=00:30:00        #This is the time that your task will run
#SBATCH --qos=30min           #You will run in this queue

# Paths to STDOUT or STDERR files should be absolute or relative to current working directory
#SBATCH --output=Unicycler_test_output     #This is the joined STDOUT and STDERR file

#This job runs from the current working directory


#Remember:
#The variable $TMPDIR points to the local hard disks in the computing nodes.
#The variable $HOME points to your home directory.
#The variable $SLURM_JOBID stores the ID number of your job.

#Sub-sampling of raw files

module load Seqtk

echo
echo === Sub_sampling ===

F1=$TMPDIR/file1
F2=$TMPDIR/file2

cp $HOME/RotationAlexander/raw_seq/VD1_S10_R1_001.fastq.gz $F1
cp $HOME/RotationAlexander/raw_seq/VD1_S10_R2_001.fastq.gz $F2

seqtk sample -s100 $F1 150000 > ${F1}_subsampled
seqtk sample -s100 $F2 150000 > ${F2}_subsampled

mkdir -p sub_sampled
cp ${F1}_subsampled $HOME/RotationAlexander/Unicycler/sub_sampled/1.fastq
cp ${F2}_subsampled $HOME/RotationAlexander/Unicycler/sub_sampled/2.fastq

echo Done
echo

module purge

# Running Unicycler on the sub sampled files

echo
echo === Running Unicycler ===

module load Unicycler
unicycler --threads $SLURM_CPUS_PER_TASK -1 $HOME/RotationAlexander/Unicycler/sub_sampled/1.fastq -2 $HOME/RotationAlexander/Unicycler/sub_sampled/2.fastq -o test --mode bold

echo Done
echo

exit
